@startuml
'https://plantuml.com/class-diagram

Class Employee {
+ fName: String
+ lName: String
+ salary: int
}

Class FileParser {
- fName: String
- delimiter : String
- input: BufferedReader
- data: ArrayList<String>

+ readFile()
+ parseData(ArrayList<String>)
+ parseAndPrintRecords()
}

Class App {
+ main(String[])
}

FileParser "1" *-- "1..*" Employee
App *-- FileParser
@enduml